# Generated by Django 5.2.1 on 2025-05-28 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flights", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flighthistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flighthistory",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_histories",
                to="flights.flight",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="extra_services",
            field=models.ManyToManyField(blank=True, to="flights.extraservice"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_histories",
                to="flights.order",
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="flights.order",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flights.flight"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_to",
                to="flights.airport",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_from",
                to="flights.airport",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flights.route"
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flights.flight"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="flights.order",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="flights.seat"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="flights.ticketclass"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ticket_class",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="flights.ticketclass",
            ),
        ),
        migrations.AddField(
            model_name="extraserviceprice",
            name="ticket_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flights.ticketclass"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("flight", "row", "seat_number")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("status", "seat")},
        ),
        migrations.AlterUniqueTogether(
            name="extraserviceprice",
            unique_together={("extra_service", "ticket_class")},
        ),
    ]
